export const RECEIVE_SELECT_CLOTHES_TYPE = 'RECEIVE_SELECT_CLOTHES_TYPE';
export const RECEIVE_SELECT_CLOTHES_IMG = 'RECEIVE_SELECT_CLOTHES_IMG';
export const RECEIVE_CLEAR_PARAMS = 'RECEIVE_CLEAR_PARAMS'
export const RECEIVE_CLEAR_CLOTHES_IMG = 'RECEIVE_CLEAR_CLOTHES_IMG';